security:
  enable_authenticator_manager: true
  encoders:
    App\Entity\User:
      algorithm: auto
  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
    ROLE_DAD:  [ROLE_USER, ROLE_PARENT]
    ROLE_MUM:  [ROLE_USER, ROLE_PARENT]


  providers:

    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      #            anonymous: true
      lazy: true
      provider: app_user_provider
      user_checker: App\Security\UserChecker
      guard:
        authenticators:
          - App\Security\Guard\WebAuthenticator
      logout:
        path: app_logout
        # where to redirect after logout
        target: app_login

      # activate different ways to authenticate
      # https://symfony.com/doc/current/security.html#firewalls-authentication

      # https://symfony.com/doc/current/security/impersonating_user.html
      # switch_user: true


  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/work/flow/demands, roles: ROLE_PARENT }
    - { path: ^/work/flow/change, roles: [ROLE_DAD, ROLE_MUM] }
    - { path: ^/work/flow, roles: ROLE_USER }
    # - { path: ^/profile, roles: ROLE_USER }
